version: '3'
services:
  db:
    image: mdillon/postgis:latest
#    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh
    restart: on-failure