# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import oral_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to=oral_history.models.my_awesome_upload_function, validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('pic', models.ImageField(blank=True, null=True, upload_to=oral_history.models.my_awesome_upload_function, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'ppm', b'grib', b'im', b'blp', b'rgba', b'rgb', b'jpx', b'h5', b'jpe', b'jpf', b'jpg', b'fli', b'jpc', b'sgi', b'gbr', b'pcx', b'mpeg', b'jpeg', b'ps', b'flc', b'tif', b'hdf', b'icns', b'gif', b'palm', b'mpg', b'fits', b'pgm', b'mic', b'pxr', b'fit', b'xbm', b'eps', b'emf', b'jp2', b'dcx', b'webp', b'bmp', b'bw', b'pbm', b'j2c', b'psd', b'pcd', b'ras', b'j2k', b'mpo', b'cur', b'fpx', b'ftu', b'png', b'msp', b'iim', b'wmf', b'jfif', b'tga', b'bufr', b'ico', b'ftc', b'xpm', b'pdf', b'dds', b'tiff'])])),
                ('full_name', models.TextField(max_length=60)),
                ('date', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.TextField(blank=True, max_length=70, null=True)),
                ('interview_by', models.TextField(blank=True, max_length=60, null=True)),
                ('birthplace', models.TextField(blank=True, max_length=60, null=True)),
                ('occupation', models.TextField(blank=True, max_length=70, null=True)),
                ('birth_year', models.TextField(blank=True, max_length=30, null=True)),
                ('summary', models.TextField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OralHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=60, unique=True)),
                ('byline', models.TextField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, max_length=2000, null=True)),
                ('about_html', models.TextField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('pic', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oralhistory_pic', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('tag', models.CharField(max_length=40)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oral_history.Interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oral_history.OralHistory'),
        ),
    ]
