# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oralhistory',
            name='about_html',
        ),
    ]
