# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oral_history', '0002_auto_20180427_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oralhistory',
            name='url',
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oralhistory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oralhistory',
            name='is_classroom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oralhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='summary',
            field=models.TextField(blank=True, max_length=45000, null=True),
        ),
    ]
