# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0002_remove_oralhistory_about_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='oralhistoryproject/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])]),
        ),
        migrations.AlterField(
            model_name='oralhistory',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='oralhistoryproject/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])]),
        ),
    ]
