# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0031_auto_20180502_1539'),
        ('oral_history', '0005_auto_20180502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='csdt_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_share.Project'),
        ),
        migrations.AlterField(
            model_name='oralhistory',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
