# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0007_auto_20180502_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
