# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0008_tag_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
