# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0009_auto_20180521_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='summary',
            field=models.TextField(blank=True, max_length=85000, null=True),
        ),
    ]
