# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0009_auto_20160408_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
