# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0010_auto_20160427_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
