# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0011_auto_20160713_1404'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[(b'CSNAP', b'cSnap'), (b'BLOCK', b'Blockly/Scratch')], default='CSNAP', max_length=5),
            preserve_default=True,
        ),
        migrations.DeleteModel(
            name='ApplicationType',
        ),
    ]
