# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0013_auto_20160906_1649'),
        ('project_share', '0011_auto_20160504_1019'),
    ]

    operations = [
    ]
