# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0017_auto_20170405_2153'),
        ('project_share', '0016_auto_20170407_1915'),
    ]

    operations = [
    ]
