# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0021_auto_20170724_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='display_name',
            field=models.CharField(blank=True, default=b'', max_length=70),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
