# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import project_share.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0021_auto_20170724_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=project_share.models.FileField(blank=True, null=True, upload_to=project_share.models.my_awesome_upload_function),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
