# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0022_auto_20170726_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcategory',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
