# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0023_applicationcategory_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='rank',
            new_name='rankApp',
        ),
        migrations.RenameField(
            model_name='applicationcategory',
            old_name='rank',
            new_name='rankCat',
        ),
    ]
