# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0024_auto_20170811_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('filename', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[(b'CSNAP', b'CSnap'), (b'BLOCK', b'C-Scratch'), (b'SPA', b'SinglePageApplication')], max_length=5),
        ),
        migrations.AddField(
            model_name='extensionorder',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_share.Application'),
        ),
        migrations.AddField(
            model_name='extensionorder',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_share.Extension'),
        ),
    ]
