# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0025_auto_20171003_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='filename',
        ),
        migrations.AddField(
            model_name='extension',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
