# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0026_auto_20171003_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extensions',
            field=models.ManyToManyField(through='project_share.ExtensionOrder', to='project_share.Extension'),
        ),
    ]
