# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0027_application_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mark',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
