# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import project_share.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0029_auto_20180227_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=project_share.models.FileField(blank=True, null=True, upload_to=project_share.models.my_awesome_upload_function, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'ppm', b'grib', b'im', b'blp', b'rgba', b'rgb', b'jpx', b'h5', b'jpe', b'jpf', b'jpg', b'fli', b'jpc', b'sgi', b'gbr', b'pcx', b'mpeg', b'jpeg', b'ps', b'flc', b'tif', b'hdf', b'icns', b'gif', b'palm', b'mpg', b'fits', b'pgm', b'mic', b'pxr', b'fit', b'xbm', b'eps', b'emf', b'jp2', b'dcx', b'webp', b'bmp', b'bw', b'pbm', b'j2c', b'psd', b'pcd', b'ras', b'j2k', b'mpo', b'cur', b'fpx', b'ftu', b'png', b'msp', b'iim', b'wmf', b'jfif', b'tga', b'bufr', b'ico', b'ftc', b'xpm', b'pdf', b'dds', b'tiff'])]),
        ),
    ]
