# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0032_auto_20180521_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='race',
        ),
    ]
