# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import project_share.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0033_auto_20190201_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State or Province'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('CSNAP', 'CSnap'), ('BLOCK', 'C-Scratch'), ('SPA', 'SinglePageApplication'), ('OHP', 'Oral History Project')], max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='application_screenshot/'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=project_share.models.FileField(blank=True, null=True, upload_to=project_share.models.my_awesome_upload_function, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])]),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_path',
            field=models.FileField(upload_to='files/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when_created',
            field=project_share.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when_modified',
            field=project_share.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Last Changed'),
        ),
    ]
