# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_post_read_time'),
    ]
