# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_auto_20170613_1602'),
        ('blogposts', '0008_auto_20170613_1634'),
    ]

    operations = [
    ]
